---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# aidr

<!-- badges: start -->
<!-- badges: end -->

The goal of aidr is to collect together a set of R functions that I otherwise
keep on recreating in most projects.

## Installation

You can install the development version of aidr from [GitHub](https://github.com/) with:

``` r
# install.packages("pak")
pak::pak("ryanraaum/aidr")
```

## Usage

There are a few different categories of functions in the package, listed below.

### Dealing with missing data of various sorts

```{r example}
library(aidr)

this_exists("this does exist")
this_exists(c(1, 2)) # so does this
this_exists(NA) # but this does not
this_exists(NULL) # this also does not
this_exists(c()) # neither does this (is empty)
this_exists(list()) # nor this
this_exists(c(1, 2, NA)) # BUT this does (vector has at least one non-NA)

this_is_singular(1) # TRUE
this_is_singular(c(1, 1)) # TRUE, only one unique value
this_is_singular(c(1, 2)) # FALSE
this_is_singular(c(1, NA)) # anything with missing data is FALSE

this_or_empty_string("this")
this_or_empty_string(NA)
this_or_empty_string(NULL)
this_or_empty_string(c("this", NA))

this_or_empty_string(list("a", "b")) # NOTE: lists are *simplified*
this_or_empty_string(list(NULL, NULL))

this_or_na("this")
this_or_na(NA)
this_or_na(NULL)
this_or_na(c("this", NA))
```

